# Generated by Django 3.2.21 on 2024-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='apex_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='apex_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='ball_speed_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='ball_speed_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='carry_distance_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='carry_distance_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='flat_carry_distance_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='flat_carry_distance_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='flat_total_distance_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='flat_total_distance_range',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='strokes_gained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_distance_premium',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='total_distance_range',
            field=models.FloatField(),
        ),
    ]
