# Generated by Django 3.2.21 on 2024-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_data', '0002_auto_20241008_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='launch_direction',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
