# Generated by Django 3.2.21 on 2024-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf_data', '0003_alter_data_launch_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='prox_to_hole',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='target',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
